{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: non-resource-url-metrics-access
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}
