apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: demo
  name: {{ .Release.Name }}
data:
  allow-snippet-annotations: "false"
  file.yaml: |
    global:
      cluster: undefined-name
{{- if .Values.jobs }}
    jobs:
{{- range $job_name := .Values.jobs }}
{{- $job_file_name := printf "%s/%s.yaml" "jobs" $job_name }}
{{ $.Files.Get $job_file_name | indent 6 }}
{{- end }}
{{- end }}
