---
apiVersion: batch/v1
kind: Job
metadata:
  name: decrease-replicas-pre-install
  generateName: decrease-replicas-pre-install
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Chart.Name }}

      volumes:
        - name: scripts
          configMap:
            name: {{ .Chart.Name }}-scripts
            defaultMode: 0744

        - name: patches
          configMap:
            name: {{ .Chart.Name }}-patches
            defaultMode: 0744

      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          volumeMounts:
            - name: scripts
              mountPath: "/etc/scripts"
              readOnly: true

            - name: patches
              mountPath: "/etc/patches"
              readOnly: true

          command: ["/bin/bash"]              

          args: ["/etc/scripts/argocd-patch.sh"]
