---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-patch
  labels:
    app: {{ .Chart.Name }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["patch"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "patch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "patch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
