---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-scripts
  labels:
    app: {{ .Chart.Name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
data:
  decrease-replicas.sh: |
{{ (.Files.Get "scripts/decrease-replicas.sh") | indent 4 }}
  argocd-patch.sh: |
{{ (.Files.Get "scripts/argocd-patch.sh") | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-patches
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
data:
  patch-argocd.yaml: |
{{ (.Files.Get "patches/argocd.yaml") | indent 4 }}
