apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:
  script.sh: |
{{ (.Files.Get "scripts/script.sh") | indent 4 }}
  decrease-replicas.sh: |
{{ (.Files.Get "scripts/decrease-replicas.sh") | indent 4 }}
