# https://crontab.guru/#*/2_*_*_*_*
# schedule: "0 */1 * * *"  # “At minute 0 past every hour.”
# schedule: "*/15 * * * *" # “At every 15th minute.”
cronjob:
  schedule: "*/1 * * * *"

image:
  repository: docker.io/silviosilva/ubuntu
  pullPolicy: IfNotPresent
  tag: ""
