#!/bin/bash

# ${HOME}/git/terraform-kubernetes-controller/manifests/charts/terraform-controller

CHART_REPOSITORY=$1

helm package "${CHART_REPOSITORY?}"

helm repo index . --url https://smsilva.github.io/helm
