apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: azurerm
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      
      tenantId: {{ .Values.azurekv.tenantId | quote }}
      vaultUrl: "https://{{ .Values.azurekv.keyVaultName }}.vault.azure.net"
      
      authSecretRef:
        clientId:
          key: ARM_CLIENT_ID
          name: {{ .Values.azurekv.secret.namespace }}/{{ .Values.azurekv.secret.name }}
        
        clientSecret:
          key: ARM_CLIENT_SECRET
          name: {{ .Values.azurekv.secret.namespace }}/{{ .Values.azurekv.secret.name }}
