---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      backoffLimit: 3

      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            app: {{ .Chart.Name }}

        spec:
          restartPolicy: Never

          volumes:
            - name: scripts
              configMap:
                name: {{ .Chart.Name }}-scripts
                defaultMode: 0744

          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}

              volumeMounts:
                - name: scripts
                  mountPath: "/etc/scripts"
                  readOnly: true

              command: ["/bin/bash"]
            
              args: ["/etc/scripts/remote-request"]
